plugins { id 'com.android.application' }android {    namespace 'org.badboyztv.toptier'    compileSdk 35    defaultConfig {        applicationId 'org.badboyztv.toptier'        minSdk 23        targetSdk 35        versionCode 7        versionName '0.7.0-tv'    }    sourceSets { main { assets.srcDirs = ['../../public']; assets.exclude '_worker.js' } }    buildTypes {        release {            minifyEnabled false            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'        }    }}dependencies {    implementation 'androidx.media3:media3-exoplayer:1.4.1'    implementation 'androidx.media3:media3-ui:1.4.1'
    implementation 'androidx.media3:media3-exoplayer-hls:1.4.1'}
