plugins { id 'com.android.application' }

android {
    namespace 'org.badboyztv.toptier'
    compileSdk 35

    defaultConfig {
        applicationId 'org.badboyztv.toptier'
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName '0.5.0-tv'
    }

    sourceSets { main { assets.srcDirs = ['../../public']; assets.exclude '_worker.js' } }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}